
- hosts: servers
  become: yes
  tasks:
  - name: make sure docker is installed
    apt:
      name: docker.io
      state: latest
      update_cache: yes  #This is the same as doing "sudo apt update"
      
  - name: ensure docker compose is installed
    apt:
      name: docker-compose
      state: latest
      update_cache: yes

  - name: Added user to docker group
    user:
      name: vagrant
      groups: docker